name: PR Test Cases

on:
  push:
    paths:
      - '**.md'
    tags:         
      - 'v**' 
      
jobs:
  test:
    name: Test Cases
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}

    - name: print
      run: echo "https://github.com"
